[project]
name = "elemental-analyze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chemparse>=0.3.2",
    "cvxpy>=1.6.5",
    "ecos>=2.0.14",
    "numpy>=2.2.5",
]
